version: "3.9"

services:
  mariadb:
    image: bitnamilegacy/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - moodle-network
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

  moodle:
    image: bitnamilegacy/moodle:4.4
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_SKIP_BOOTSTRAP=no
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    networks:
      - moodle-network

  ltitool:
    build: 
      context: ./ltitool
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=supersecret
      - OAUTH_SECRET=lti_oauth_secret
    networks:
      - moodle-network

volumes:
  moodle_data:
  mariadb_data:
  moodledata_data:

networks:
  moodle-network:
    driver: bridge