FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ltitool.py .

ENV FLASK_APP=ltitool.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
